### ISSUE TITLE
Can't download files on AWS Lambda

### ISSUE THREAD

**Issue by pbpaes1** [soumilshah1995/Selenium-on-AWS-Lambda-Python3.7#2]
Hi everyone,

I'm trying to run a selenium scraper on AWS Lambda using the chrome_headless.zip file. Apparently the code is being executed correctly until the end. The code performs login in a website and then clicks on a button to download a .xlsx file. It sends a messagem when the execution is over, but I can't find the file on the /tmp folder.

I've already tried to specify the download directory, expand the max time and memory for the execution but nothing seems to work.
Copying the options in [this](https://stackoverflow.com/questions/73395376/aws-lambda-download-a-file-using-chromedriver) question, which seems a very similar problem, has not worked.

Does anyone know what I'm doing wrong? Or even if it is possible to download files like this on AWS Lambda?

**Comment by soumilshah1995** [comment]
use aws s3 to dump and download file closing this since its not bug
